### ISSUE TITLE
test sd card write failure robustness / define and document expected behavior

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/SensorGrid#54]
In particular, we need well defined behavior around what happens when we pull the SD card during a time when data needs to get written to it.

To the extent possible, we want to protect from corrupted SD files due to pulling the card while a write is happening. If there is anything we can do about this, we should, but I suspect little can be done.

In a more general sense, though, we want to be sure the device will keep running and logging if a card has been pulled and then replaced where a write operation happens while the card is missing.

**Comment by jdk27** [comment]
The SD card write seems to be robust. When the card is present it writes, and if the card is removed and replaced it can resume writing the current data. There could be issues with removing card during a write. Maybe Flash "writing" on oled before it writes to diminish chances of user pulling the card at that moment.
