### ISSUE TITLE
in the setXTimeout functions, rename variables to be more clear

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/SensorGrid#56]
https://github.com/NUKnightLab/SensorGrid/blob/0b4df4beab246d53ffb9f27bd7ae3f560a15f511/SensorGridPM/runtime.cpp#L132

Time variables could be more clear. E.g. heartbeat should be heartbeat_time, sample should be sample_time, etc.

**Comment by jdk27** [comment]
changed heartbeat to heartbeat_time and sample to sample_time
